### PR TITLE
rename pslamch to pslamch10 to avoid symbol collision with Scalapack

### PR DESCRIPTION
**Pull request by davydden**
fixes https://github.com/opencollab/arpack-ng/issues/50

### CODE REVIEW

**Comment by davydden** [comment]
@sylvestre  ping.

**Comment by davydden** [comment]
@sylvestre ping-ping.

**Comment by sylvestre** [comment]
Sorry, I don't know why I didn't merge that earlier :)

**Comment by davydden** [comment]
no worries, thanks a lot!

**Pull request merged**
