### PR TITLE
execute the dnsimp test in the right directory

### PR DESCRIPTION
**Pull request by rwirth**
Fixes opencollab/arpack-ng#14

### CODE REVIEW

**Comment by sylvestre** [comment]
This breaks the test. Could you fix the issue?

**Comment by rwirth** [comment]
Forgot to add the script to `EXTRA_DIST`. Works now.

**Comment by turboencabulator** [comment]
The AC_CONFIG_LINKS macro in configure.ac should already handle this, by making either a symlink or a copy of testA.mtx in the build directory.  This change should be unnecessary if that macro is working correctly.
This may have been a problem from before I added the macro.  Have you tried building from master lately?

**Comment by sylvestre** [comment]
FYI, I simplified the patch in commit 82de5c6bed8a2600d311f1ca27dd843e12b5eacd

**Pull request merged**
