### PR TITLE
allow triggering GitHub Actions for PRs

### PR DESCRIPTION
**Pull request by dimpase**
as discussed on #317 - PRs are not pushes, so it needs to be said explicitly.

See https://github.com/opencollab/arpack-ng/pull/317#issuecomment-932994090

### CODE REVIEW

**Comment by dimpase** [comment]
Should we also disable these Docker tests, failing for reasons not really relevant?
(And try to fix them in another PR?)

**Comment by fghoussen** [comment]
Docker tests fail on PR but are OK on master ?!...

**Comment by mkoeppe** [comment]
If your tests use secrets, this would explain it: Actions on PRs don't get access to secrets

**Comment by fghoussen** [comment]
Yes, following github action doc, I defined secrets on opencollab github account and my account (which fired the first PR - OK at my side https://github.com/fghoussen/arpack-ng/commits/master). I believed after the first PR merged, opencollab secrets would be used for PRs onto opencollab (as they are rebased on opencollab repo)... @mkoeppe : do you know how to get this (secrets for docker runs) to work on PRs too ?

**Comment by mkoeppe** [comment]
I don't know anything about your use case; but note that if arbitrary users can run these workflows by submitting a PR, the secrets would be trivial to read out by arbitrary users

**Comment by fghoussen** [comment]
#323: trying `pull_request_target` from https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

**Pull request merged**
