### PR TITLE
Give up forcing the initial residual to be in the range of the operator OP after a restart (Closes: #142).

### PR DESCRIPTION
**Pull request by caliarim**

### CODE REVIEW

**Comment by sylvestre** [comment]
@ntamas Could you please check that this PR fixes your problem?
Thanks

**Comment by sylvestre** [comment]
@ntamas Could you please check that this PR fixes your problem?
Thanks
@caliarim Would be great if you could also run the tests as part of the cmake process! :)

**Comment by caliarim** [comment]
@sylvestre If I run
```
$ mkdir build
$ cd build
$ cmake -D EXAMPLES=ON -D MPI=ON -D BUILD_SHARED_LIBS=ON ..
$ make
```
I see that bug_142 and bug_142_gen are run. Do you mean something different?

**Comment by sylvestre** [comment]
Oh, my bad, I missed the second file :(
sorry

**Comment by ntamas** [comment]
@sylvestre I have tested the pull request -- everything seems okay for me (tested with the test cases in igraph).

**Comment by sylvestre** [comment]
Thanks, let's merge it then :)

**Pull request merged**
