### PR TITLE
[CI] Windows job: run full test suite.

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

Checking if db55a7f enables to run full test suite on windows.

### CODE REVIEW

**Comment by fghoussen** [comment]
@juanjosegarciaripoll: what would be the needed minimal changes to fix this? (don't hesitate to push on top of this PR)

**Comment by juanjosegarciaripoll** [comment]
I have to look at this again, because the canonical way of declaring tests seemed to interfere with your build configuration and use of global variables. Will get back once I find a solution.

**Comment by fghoussen** [comment]
@juanjosegarciaripoll: did you had time to look at this? Would be nice to have minimal changes to run on windows.

**Comment by fghoussen** [comment]
Fixed by #392

**Pull request closed without merging**
