### PR TITLE
CI: add fedora build via docker run.

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

add fedora build to CI

### CODE REVIEW

**Comment by fghoussen** [comment]
@rathann: no idea how to do this on fedora !... (packages names ?)

`
apt-get -y install git gfortran gcc g++ libblas-dev liblapack-dev openmpi-bin libopenmpi-dev automake autoconf libeigen3-dev
`

If the fedora docker run has not (?) by default one of them installed this will fail !... :D

**Comment by rathann** [comment]
Also, you want `gcc-c++` for compiling C++ code.

**Comment by rathann** [comment]
Judging by the travis-ci log, you're still missing `libtool` and `gcc-gfortran` build dependencies on Fedora.

**Comment by rathann** [comment]
Since you're doing a MPI build, you need to:
``` shell
. /etc/profile.d/modules.sh
module load mpi/openmpi-x86_64
```
before running `configure`. This is because Fedora ships both OpenMPI and MPICH as parallel-installable and supports switching between implementations using environment modules.

**Comment by fghoussen** [comment]
OK, let's follow you, not (yet !) familiar with fedora

**Comment by fghoussen** [comment]
Don't know what "rawhide" was so I google it ! :D 
Sounds like rawhide is the dev version of fedora (as unstable debian ?) : maybe not stable enough for a CI ?!...

**Comment by rathann** [comment]
Why are you trying to run `updatedb`? That's part of `mlocate`, which you definitely don't need for this build.

**Comment by fghoussen** [comment]
> Why are you trying to run updatedb? 

No reason, just trying !... Don't get why 6b59e6c fails with `/usr/bin/ld: cannot find -lmpi`

**Comment by fghoussen** [comment]
@rathann : do you get why this fails ? I you want a fedora build, I let you the hand on it.

**Comment by fghoussen** [comment]
@rathann : do you build arpack-ng on fedora with cmake ? I think the problem lies with autotools 

```
>> git grep noopt
PARPACK/SRC/MPI/Makefile.am:noinst_LTLIBRARIES = libparpack@LIBSUFFIX@_noopt.la
PARPACK/SRC/MPI/Makefile.am:libparpack@LIBSUFFIX@_noopt_la_SOURCES = pslamch10.f pdlamch10.f
PARPACK/SRC/MPI/Makefile.am:libparpack@LIBSUFFIX@_noopt_la_FFLAGS = -O0
PARPACK/SRC/MPI/Makefile.am:libparpack@LIBSUFFIX@_la_LIBADD = libparpack@LIBSUFFIX@_noopt.la \

```

**Comment by fghoussen** [comment]
@sylvestre: check out b3b310f, I think `add_test` is missing (independently of this PR)

**Comment by fghoussen** [comment]
indeed, some tests were not run:

```
The following tests FAILED:
	 72 - pcndrv1_ex (Failed)
	 73 - pdndrv1_ex (Failed)
	 74 - pdndrv3_ex (Failed)
	 75 - pdsdrv1_ex (Failed)
	 76 - psndrv1_ex (Failed)
	 77 - psndrv3_ex (Failed)
	 78 - pssdrv1_ex (Failed)
	 79 - pzndrv1_ex (Failed)
Errors while running CTest

```

**Comment by fghoussen** [comment]
No way to get `configure` to work (?) on fedora, but, `cmake` should be OK

**Comment by fghoussen** [comment]
BTW, this is testing `fedora:rawhide`. Not sure if this is stable enough for a CI. You may prefer `fedora` ?

**Comment by fghoussen** [comment]
Should be merged !

**Comment by fghoussen** [comment]
@sylvestre : can you merge that ? will conflict with #209

**Pull request merged**
