### PR TITLE
[BUG FIX] CMake: use ${PROJECT_SOURCE_DIR}.

### PR DESCRIPTION
**Pull request by fghoussen**
.. is OK only when the BUILD dir in under the root dir.

### CODE REVIEW

**Comment by sylvestre** [comment]
guys, would like more permissions on arpack?
Right now, I am the only one approving PR and this isn't great (bus factor).

**Comment by fghoussen** [comment]
I missed this message ! :D The last PR I PR'ed (if you like to merge it ?) is my last one !

**Comment by sylvestre** [comment]
Too bad!

**Comment by fghoussen** [comment]
For icb !... :D I can help to maintain if necessary !

**Pull request merged**
