### PR TITLE
Add parpack files in the coveralls report.

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

fixing issue #182 ?

### CODE REVIEW

**Comment by sylvestre** [comment]
This is expected: more code, not enough tests :)

**Comment by sylvestre** [comment]
many thanks

**Comment by sylvestre** [comment]
"0 of 0 changed or added relevant lines in 0 files are covered." => hmm, no more files?

**Comment by fghoussen** [comment]
> hmm, no more files?

I guess no !...

**Pull request merged**
