### PR TITLE
stat: initialize common block.

### PR DESCRIPTION
**Pull request by fghoussen**

### CODE REVIEW

**Comment by fghoussen** [comment]
b43933a fails but shouldn't ?!... Restart it or skip/kill it :D

**Comment by fghoussen** [comment]
pushed forced with old-fortran-style !...

**Comment by fghoussen** [comment]
Giving up trying to write F77 (I have no F77 compiler) !... :D

**Comment by caliarim** [comment]
@fghoussen: I speak F77, what do you need? Initializations for debug.h and stat.h?

**Comment by fghoussen** [comment]
@caliarim : try to move `debug_init.f90` / `stat_init.f90` into `debug_init.f` / `stat_init.f`, make changes to get compilation/link OK... And check out if travis CI is still OK ?! This way all F77 (resp. F90) code would be compiled by a F77 (resp. F90) compiler. You can PR at my side, or, wait this PR to be merged

**Comment by fghoussen** [comment]
I did all that... But forgot the 7 chars names rule ! Tryed to push something to try that. Thanks

**Comment by caliarim** [comment]
I also forgot the 6 chars rule, in a first moment. Then, I used ftnchek -f77=all

**Comment by fghoussen** [comment]
Waow ! Seems to work :D Thanks to all of you guys !

**Comment by sylvestre** [comment]
maybe add this to the changelog?

**Pull request merged**
