### PR TITLE
Add back the coveralls push

### PR DESCRIPTION
**Pull request by sylvestre**
bring back the code coverage

### CODE REVIEW

**Comment by fghoussen** [comment]
Oh ?! Didn't noticed that. No, don't know what's going on ?!... Would say this is broken since .travis.yml has been rewritten (by me !...) with `stages` instead of `script` ?

**Comment by fghoussen** [comment]
Got it ! Look at the logs
> The job exceeded the maximum log length, and has been terminated.

You need to use travis_wait : https://docs.travis-ci.com/user/common-build-problems/

**Comment by fghoussen** [comment]
After thinking of it, it may not work. If so, revert `travis_wait` but try `make all test > /dev/null  ` : the message says log length limit is reached (not the time limit - I thought at first it was that)

**Comment by fghoussen** [comment]
worked ! :D still weird : it was working before ?!...

**Comment by sylvestre** [comment]
I guess the log was shorter?

**Comment by fghoussen** [comment]
yeah... maybe the log was previously touching the limit.
arpackmm is likely to have increased coverage : is so, you may see the coverage rate increased.

**Pull request merged**
