### PR TITLE
CI: Setup workflow for MinGW-w64 CLANG64

### PR DESCRIPTION
**Pull request by MehdiChinoune**
## Pull request purpose

This setup CI workflow for MSYS2/CLANG64
It completes the work done in #412, The workflow was failing, but we fixed that issue.

## Detailed changes proposed in this pull request

- Setup CI workflow for MinGW-w64 CLANG64
- Test with MPI=ON/OFF
- Test with INTERFACE64=ON/OFF

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
ping!

**Comment by fghoussen** [comment]
Can you update the change log?

**Comment by fghoussen** [comment]
Why closing?

**Comment by MehdiChinoune** [comment]
3 weeks, not merged!

**Pull request closed without merging**
