### PR TITLE
Arpack solver

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

enhancement : extract arpackSolver from arpackmm. Based on #216.

### CODE REVIEW

**Comment by sylvestre** [comment]
fails on ubuntu precise, could you please have a look?

**Comment by fghoussen** [comment]
Yes. AFK for the week-end. Will do that next week.

**Comment by fghoussen** [comment]
Had to redesign a bit the arpackmm test. But it's essentially the same. Hope coverage will not break.

**Comment by fghoussen** [comment]
Rerun interface64 job ? (broken package fetch on updgrade)

**Comment by fghoussen** [comment]
No related with the PR. ILP64 update is broken.

**Pull request merged**
