### PR TITLE
[TravisCI] : Add windows job.

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

Related to #227

### CODE REVIEW

**Comment by fghoussen** [comment]
no arm, no chocolate... no choco, no way

**Comment by fghoussen** [comment]
OK, seems we have a starting point

**Comment by fghoussen** [comment]
... Nope breaks unix builds !

**Comment by fghoussen** [comment]
Should be OK... wait and see

**Comment by fghoussen** [comment]
@sylvestre : 88a142a7058d1769eb810ee7c04d4d7dab6b6f07 git-clone triggers some kind of ssh (// wget) from the web. Unlikely but may be unstable : do we agree on that ?

**Comment by sylvestre** [comment]
@fghoussen you can retrigger the task if it fails to mitigate the issue

**Comment by fghoussen** [comment]
No much time now. Posted question on https://travis-ci.community/. Hope to get answer/idea.

**Comment by fghoussen** [comment]
should I close this ?

**Comment by sylvestre** [comment]
As you wish :)

**Comment by fghoussen** [comment]
I think we reached the end of the road here... Closing sounds logical !

**Pull request closed without merging**
