### PR TITLE
[BUG FIX] arpackmm: fix restart.

### PR DESCRIPTION
**Pull request by fghoussen**
* Fixing issue401.

* Fixing issue215 with shift.

### CODE REVIEW

**Comment by szhorvat** [comment]
It seems to me that this PR only makes changes to the arpackmm interface, but not to ARPACK itself. Issue #401 is unrelated to arpackmm. Am I missing anything?

**Comment by szhorvat** [comment]
I see that you added a test with the matrix from #401, but I don't see how the starting `resid` is set. #401 is reproducible with certain (reasonable) starting `resid` vectors. Can you try these? See https://github.com/opencollab/arpack-ng/issues/401#issuecomment-1435530450

**Comment by fghoussen** [comment]
> It seems to me that this PR only makes changes to the arpackmm interface, but not to ARPACK itself.

Correct. To me the 401/215 issues are not related to arpack, but in the misuse of it (in arpackmm, igraph, octave) like it often happens as the doc is no-great!... Indeed, this PR fixes arpackmm only

> Issue #401 is unrelated to arpackmm. Am I missing anything?

Correct. #215 is unrelated to #401, but, on the way to fixing #401, I had the same issue than #215, so I had to look at that too. In the end, I was able to get arpack to work on both #401 and #215 following the guidelines explained here: https://github.com/fghoussen/arpack-ng/tree/arpackmm#faq.

My understanding (may be wrong !...) is that:

- in #401, it looks like you set your initial vector `v` in the wrong place https://github.com/opencollab/arpack-ng/issues/401#issuecomment-1439075297: `v` should not be placed in `resid`. Starting from here, various BLAS on vaious distros may end up in different behavior depending on numerical values you have at the initialization. 

- in #215, I guess `resid ` was set to zero so that `info = -9 Starting vector is zero` is to be expected and is actually 100% logical! :) As `A` is zero and the eigen value to find is zero too, you *need* to shift just a bit in order to start arpack with something which is *not* zero (i.e. with a `resid = Av - lamdba*v` which is not zero at start). This looks to me like a very specific (corner ?! :) ) case. I guess here too depending on numerical  values you have at the initialization, you may succeed or not to start arpack.


> I see that you added a test with the matrix from #401, but I don't see how the starting `resid` is set. 

For from-scratch runs:
https://github.com/fghoussen/arpack-ng/blob/99bc00e1b18cfce3eb0248b4375852b5a4174776/EXAMPLES/MATRIX_MARKET/arpackSolver.hpp#L734

For restart runs:
https://github.com/fghoussen/arpack-ng/blob/99bc00e1b18cfce3eb0248b4375852b5a4174776/EXAMPLES/MATRIX_MARKET/arpackSolver.hpp#L684

> #401 is reproducible with certain (reasonable) starting `resid` vectors. Can you try these? See [#401 (comment)](https://github.com/opencollab/arpack-ng/issues/401#issuecomment-1435530450)

You can do *all* tests (likely more than one!) you'll need by yourself:

- run arpackmm once: this will produce `arpackSolver.resid.out` and `arpackSolver.v.out` as explained in `arpackmm --help`
- Put whatever values you want to test in `resid` and `v` through theses files and re-run arpackmm with restart option `arpackmm --restart ..... --verbose 3` and maybe verbose option: restart with your initial vector.

All tests I did at the command line seems to work now as I managed `arpackmm` to never let `resid` to zero (lesson learned from #215)

**Comment by fghoussen** [comment]
> in https://github.com/opencollab/arpack-ng/issues/215, I guess resid was set to zero so that info = -9 Starting vector is zero is to be expected and is actually 100% logical! :) As A is zero and the eigen value to find is zero too, you need to shift just a bit in order to start arpack with something which is not zero (i.e. with a resid = Av - lamdba*v which is not zero at start).

Another possible reason for 215 issue may be `v` init that in this cas must *not* be exactly zero but some small values: https://github.com/fghoussen/arpack-ng/blob/99bc00e1b18cfce3eb0248b4375852b5a4174776/EXAMPLES/MATRIX_MARKET/arpackSolver.hpp#L741 

The problem is that they are lots of misleading examples out there on how you could use arpack... Not always clear to understand what to do. `for (a_int n = 0; n < ldv*nbCV; n++) v[n] = zero; // Avoid "bad" starting vector.` is something I got from one of these samples... In #215 setting *both* `resid` and `v` to *exactly* zero means `resid` is zero at start and will prevent arpack from starting...

**Comment by fghoussen** [comment]
Seems `make distcheck` fails: OK here, no idea why!?... Any clue is welcomed

**Pull request merged**
