### PR TITLE
[CI] Fix docker error: toomanyrequests You have reached your pull rat…

### PR DESCRIPTION
**Pull request by fghoussen**
Try fixing #309

### CODE REVIEW

**Comment by fghoussen** [comment]
No-op commit ?!...

**Comment by fghoussen** [comment]
@sylvestre: travis CI seems to be back. Let's see if docker runs...

**Comment by fghoussen** [comment]
@sylvestre : do you have a plan for opencollab travis-ci account ?

image

**Comment by fghoussen** [comment]
Try running arm/ppc ? @sylvestre : what do you think ?

**Comment by fghoussen** [comment]
Travis down.
GH : osx / docker OK, old distros (bionic to precise) / coverage (which sounds bad more than old distros) KO.
@sylvestre : is GH a good move ? Or the only one we could take ? What do you think ?

**Comment by dimpase** [comment]
Travis went expensive last year, or when was that, so no, it's not free any more even for open-source (only few runs per month, something like this). GitHub Actions are the right move.

**Comment by dimpase** [comment]
Can we split this PR into two, leaving the travis-related stuff aside?

**Comment by fghoussen** [comment]
> Travis went expensive last year, or when was that, so no, it's not free any more even for open-source. GitHub Actions are the right move.

Didn't know ! Thanks for the tip :D

> Can we split this PR into two, leaving the travis-related stuff aside?

Still didn't decided what to do here.
For me : drop coverage (too bad), drop old distro (precise, ...), drop travis and move on to gh
@sylvestre  : what do you think ?

**Comment by fghoussen** [comment]
@sylvestre : if you don't want to drop coverage, you may try https://github.com/codecov/cpp-11-standard

**Comment by fghoussen** [comment]
Closing as it served as baseline for another merged PR.

**Pull request closed without merging**
