### PR TITLE
arpackmm: add --cpxPb option (run with zn[ae]upd).

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

arpackmm enhancement

## Detailed changes proposed in this pull request

allow to test with complex matrices

### CODE REVIEW

**Comment by fghoussen** [comment]
Let's see if this will be OK !... If so I have another PR to push after this one

**Comment by sylvestre** [comment]
Maybe references the license of these matrices in https://github.com/opencollab/arpack-ng/blob/master/COPYING ?

**Comment by sylvestre** [comment]
I re-triggered the build to verify the impact on the code coverage

**Comment by fghoussen** [comment]
> Maybe references the license of these matrices in https://github.com/opencollab/arpack-ng/blob/master/COPYING ?

OK, I'll do that

> I re-triggered the build to verify the impact on the code coverage

I need to rebase (+ add COPYING modif) on master once the coveralls PR is merged for that, no ?

**Comment by fghoussen** [comment]
> Maybe references the license of these matrices in https://github.com/opencollab/arpack-ng/blob/master/COPYING ?

The matrices are the ones already used in EXAMPLES/SYM and EXAMPLES/NONSYM : I guess there is no need to modify COPYING (these examples are simple : that's why I started from them - nothing new here !)

**Comment by fghoussen** [comment]
tell me if you want me to rebase

**Comment by sylvestre** [comment]
yeah needs a rebase please

**Comment by fghoussen** [comment]
on  e67badf coverage has increased +4.4% if i am not mistaken.
I am about to rebase this PR.

**Comment by fghoussen** [comment]
rebased. should increase coverage again...

**Comment by fghoussen** [comment]
... +0.07 ! :D

**Comment by sylvestre** [comment]
Surprisingly small ! :)

**Pull request merged**
