### PR TITLE
Update SONAME to reflect the change in source code

### PR DESCRIPTION
**Pull request by renierm**
Update the SONAME for the latest version as discussed in https://github.com/opencollab/arpack-ng/issues/140.

### CODE REVIEW

**Comment by sylvestre** [comment]
First, many thanks for that

Two comments:
* I think we should move that into the configure.ac to have a single declaration
* also update the cmake build

If you don't know how to do that, please let me know :)

**Comment by renierm** [comment]
I will get back to this sometime this week, just a bit swamped with work :-)

**Comment by renierm** [comment]
I have pushed the change to only define SONAME once in configure.ac which is then propagated to the relevant Makefile.am files. The value is currently directly set in configure.ac which is maybe not be best place as this could be read from an environment variable?

I am not quite sure what needs to happen with regards to the cmake build.

**Comment by sylvestre** [comment]
I didn't forget about you. We (or maybe I) need to fix the cmake stuff before landing this patch.

**Comment by sylvestre** [comment]
Closing until someone propose a cmake fix too.

**Comment by fghoussen** [comment]
Not an expert here. Looked quickly to https://cmake.org/cmake/help/v3.13/prop_tgt/SOVERSION.html.
Seems this is "just" about adding :
set(SOVERSION "2:1")
in CMakeLists.txt ? Or something similar ?

**Pull request closed without merging**
