### PR TITLE
[TravisCI] OS X: running the whole test suite.

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

Was told this is supposed to work ?!.... checking... Related to #6

### CODE REVIEW

**Comment by fghoussen** [comment]
Nope !...

> FAIL icb_arpack_cpp
> ERROR: iparam[4] 4, nev 9, info -9999
> libc++abi.dylib: terminating with uncaught exception of type std::domain_error: Error inside ARPACK routines

**Comment by fghoussen** [comment]
@sylvestre : closing ? or want to keep partial build/test with veclib ?

**Comment by fghoussen** [comment]
@sylvestre : seems `-ff2c` make all tests pass... not sure you want to keep that kind of "switch hand-tuning"

**Comment by fghoussen** [comment]
Seems that with `-ff2c`, all tests pass on mac. Should break with MPI (at least with autotools)...

**Comment by fghoussen** [comment]
Conclusion: full build/test OK if `-ff2c` but **without** MPI. Adding MPI breaks build/test : no idea why ?!...

**Comment by fghoussen** [comment]
Unexpectedly working ?!... :D

**Comment by fghoussen** [comment]
Not sure there's more simple : I guess "switch hand-tuning" is needed on mac (not sure this could be handled by build systems in an "automatic" way)

**Comment by fghoussen** [comment]
@sylvestre: you could make build systems add flags under a "if mac", not sure this is the best thing to do... This is your decision

**Comment by sylvestre** [comment]
Could you please update the changelog to mention that we have now mac support in the CI?

**Pull request merged**
