### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by dbeurle**
Test PR on changes to the test script for the c++ arpack example.  Related to #86

### CODE REVIEW

**Comment by dbeurle** [comment]
@sylvestre Can I get a hand please with the configure build script?  I'm not familiar with autotools (millennials eh?).  Best I could find is https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx_11.html

I guess `noext` and `required` are the options?

**Comment by fghoussen** [comment]
You should not need C++11.
Why do you rewrite the all example ? This makes history messy and loose the reviewer: you just need to replace ssaupd_c (and others) with the new C++ wrappers. There is only a few lines to change.

**Comment by dbeurle** [comment]
Do you think that example is clear and easier to follow?  For example, allocating memory on the stack and heap inconsistently, casting the result from `new` and is plain confusing to a newcomer.  The example should be best practise.  You want to people to understand what is happening in the test / example code and what was there before was difficult to read and outdated.  There is no point having a C++ example if all that is different is a call to `new` and `malloc`.

**Comment by fghoussen** [comment]
This example comes from the C example (not meant for style, meant for checking it works).
I meant that to keep history clean/understandable by all people involved, it's better to stick to minimal changes only (personal opinion).

**Comment by dbeurle** [comment]
@fghoussen 
> This example comes from the C example (not meant for style, meant for checking it works).
What exactly is being checked in the C++ example?  Whether `new` or `extern "C"` works?  The C and C++ tests don't even check if the imaginary eigenvalue is correct (which they aren't on my machine).  The examples for the complex matrices are broken.

The output of an octave script
```matlab
A = sparse(diag(1:10) + I * diag(1:10)); [ei, ev] = eigs(A)
```
gives the expected result - which IIRC references ARPACK on the backend.

> I meant that to keep history clean/understandable by all people involved, it's better to stick to minimal changes only (personal opinion).

My personal opinion is that history is just that.  If that example file needs to be rewritten to be clear and show good use of the API then one commit is a price I'd be willing to pay.  If the maintainers disagree then so be it.  I'm not trying to create a mess - I'm trying to raise the quality of the C++ examples.  You can pooh pooh me at every step or you can admit it needs improvement and we can work together to make this happen.

**Comment by fghoussen** [comment]
I understand your intention which is commendable. Arpack has been written in the 70's by cavern guys with the ugly permissive fortran : it's no more maintained and has been a pain to use by everybody from the very beginning, nobody will change that now ! iso_c_binding is just a gateway: no more. There is no place for style or quality here (I wish it could). Arpack would need a top-down full re-write in modern C++ (replacing the permissive and misleading Reverse Communication Interface with modern C++ std::function) but it's so specific, tricky and time-consuming that nobody never did it. There is no way now to make arpack user-friendly (personal opinion). Same story for LAPACK, SCALAPACK and others...

**Comment by fghoussen** [comment]
Don't want to discourage you here. I tried to PR something...

**Comment by dbeurle** [comment]
I agree, the interface is horrible but the other options aren't particularly attractive either (unless you know of a good eigenvalue library?).  A google search for C++ and sparse eigenvalue solvers returns SLEPc (need to pull in PETSc), FEAST which requires sign up, ARPACK (that's why I'm here) and Spectra (doesn't seem to do complex matrices).  If there were another library that was easier to use and as well tested then other projects would switch.  That's probably why does this project exists.

That `const` PR you did is a step in the right direction in making this interface better.  At some point we're putting lipstick on a pig, I agree, but until someone wants to pony up and write this modern eigenvalue solver we're stuck with this.

Are you familiar enough with autotools to make the `c++11` check?

**Comment by fghoussen** [comment]
>What exactly is being checked in the C++ example? Whether new or extern "C" works?

Just that the C example can be compiled / link with a C++ compiler. No more.

>the interface is horrible but the other options aren't particularly attractive either 

With *PACK (LAPACK, SCALAPACK, ARPACK, ...) the interface always as cumbersome as depressive : you will be _compelled_ to live with these painful things as there is no other options... Style is out of question.

>search for C++ and sparse eigenvalue solvers

SLEPc (which uses ARPACK) is not so bad. You can check out eigen (maybe not everything is available - don't know for complex) : http://eigen.tuxfamily.org/index.php?title=Main_Page.

>That const PR you did is a step in the right direction in making this interface better.

You have no chance to have better than this. For std::complex, actually you need std to provide std::complex::c_cplx (the way std::string::c_str does)... Good luck on that !...

>Are you familiar enough with autotools to make the c++11 check?

Use ax_cxx_compile_stdcxx_11

**Pull request closed without merging**
