### PR TITLE
rename pdlamch to pdlamch10 to avoid symbol collision with Scalapack …

### PR DESCRIPTION
**Pull request by davydden**
…2.0.2 where this function is different.

should fix https://github.com/opencollab/arpack-ng/issues/18 but until https://github.com/opencollab/arpack-ng/pull/19 is merged I can't test it on my mac.

### CODE REVIEW

**Comment by davydden** [comment]
sorry to bother, could you give a quick look at this PR as it should be an easy fix of a serious bug @sylvestre .

**Comment by sylvestre** [comment]
Sorry, I missed your initial PR.
A few questions:
* Why arpack-ng has to be renamed? Why not scalapack? Looks at Debian statistics, arpack (even parallel arpack) has much more users than scalapack 
* What will happen to software already using pdlamch?
* Why pdlamch10? (the 10 ?)
* The soname dump is missing as the ABI changed.

For now, I don't think we can rename this function. The impact might too big.

**Comment by davydden** [comment]
*  i think `arpack-ng` has to be renamed as it is actually a copy-pasted function (veresion `1.0`) from `scalapack` to be used inside `arpack` software. To my understanding it was not written by arpack authors. During last 10-15 years this function changed upstream as scalapack evolved. So i think it makes sense to renamed the copy-pasted function to something else.

*  if there is a software which used `pdlamch` as provided by `arpack` then it will certainly be broken. But i would argue that it's a bad practice anyway. I think the issue here is that `arpack` should not have copy-paste the function but declare a dependency (requirement) of `scalapack` for build and then use inside this single function. Then this issue would have been obvious the moment `scalapack` interface changed. 

* `pdlamch10` because it's version `1.0`. Could as well be 99, but i thought `10` makes more sense.

Keep in mind that if you don't rename this function then the whole arpack is somewhat broken as it would lead to segmentation fault in certain scenariou (which is very hard to trace!) as i discussed in the issue https://github.com/opencollab/arpack-ng/issues/18 . 
Possible user cases is combining `arpack` and `mumps` (a popular parallel sparse direct solver) or any other solver for that matter which is build against `scalapack`. I would be happy to rework the PR if you have any other solution in mind to avoid symbol conflict.

**Comment by sylvestre** [comment]
No, your rational is fine! Thanks for taking the time to explain.

**Comment by sylvestre** [comment]
I guess it is too hard to write a non regression test for this?

**Comment by davydden** [comment]
i am not sure you can do any tests here because the problem appears not when you compile `arpack` (at that stage even all tests could be fine), but when you actually link some executable which happen to have `libarpack` and `libscalapack` in its linking flags.

So if the user (or a third party library) is clever to check for symbol clash (and if so disable arpack or another library), then the segmentation fault can be avoided. But I don't think you can do it on `arpack` side.

I don't know Fortran much, perhaps there could be some low-level solutions how to avoid the issue, but supposedly they would be equivalent to a simple rename.

**Comment by sylvestre** [comment]
Ok, thanks!

**Pull request merged**
