### PR TITLE
Dlaqrb

### LINKED ISSUE #7: test failure on x86_64-linux: bug_1315_single
I'm packaging arpack-ng for GNU Guix and encountered a test failure:

~~~
...
make  check-TESTS
make[2]: Entering directory '/buildtmp/nix-build-arpack-ng-3.2.0.drv-0/arpack-ng-3.2.0/TESTS'
make[3]: Entering directory '/buildtmp/nix-build-arpack-ng-3.2.0.drv-0/arpack-ng-3.2.0/TESTS'
FAIL: bug_1315_single
PASS: dnsimp
PASS: bug_1315_double
make[4]: Entering directory '/buildtmp/nix-build-arpack-ng-3.2.0.drv-0/arpack-ng-3.2.0/TESTS'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/buildtmp/nix-build-arpack-ng-3.2.0.drv-0/arpack-ng-3.2.0/TESTS'
============================================================================
Testsuite summary for arpack-ng 3.2.0
============================================================================
# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See TESTS/test-suite.log
Please report to https://github.com/opencollab/arpack-ng/issues/
============================================================================
Makefile:699: recipe for target 'test-suite.log' failed
...
~~~

These are the contents of the log file:

~~~
===========================================
   arpack-ng 3.2.0: TESTS/test-suite.log
===========================================

# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: bug_1315_single
=====================

999.997742
998.996643
997.997253
996.997314
995.996338
993.996948
~~~

I'm compiling with gfortran 4.8.4 and linking against ATLAS 3.10.2.

### LINKED ISSUE #11: Test failure on i686-linux-gnu with ATLAS
I built arpack-ng with ATLAS 3 installed by full LAPACK interface. Then tried to run tests and get a test failure in 'dnsimp'
This is test-suite log:

 =========================================
   arpack-ng 3.1.3: TESTS/test-suite.log
 ==========================================

 # TOTAL: 2
 # PASS:  1
 # SKIP:  0
 # XFAIL: 0
 # FAIL:  1
 # XPASS: 0
 # ERROR: 0

 .. contents:: :depth: 2

FAIL: dnsimp
 ============

 At line 194 of file /media/home/programs/arpack-ng-3.1.4/TESTS/dnsimp.f (unit = 10, file = '')
 Fortran runtime error: File 'testA.mtx' does not exist

### LINKED ISSUE #16: arpack-ng 3.2.0 test failure on x86_64-linux: bug_1315_double
$./configure 
```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for g77... no
checking for xlf... no
checking for f77... no
checking for frt... no
checking for pgf77... no
checking for cf77... no
checking for fort77... no
checking for fl32... no
checking for af77... no
checking for xlf90... no
checking for f90... no
checking for pgf90... no
checking for pghpf... no
checking for epcf90... no
checking for gfortran... gfortran
checking whether the Fortran 77 compiler works... yes
checking for Fortran 77 compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU Fortran 77 compiler... yes
checking whether gfortran accepts -g... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gfortran option to produce PIC... -fPIC
checking if gfortran PIC flag -fPIC works... yes
checking if gfortran static flag -static works... yes
checking if gfortran supports -c -o file.o... yes
checking if gfortran supports -c -o file.o... (cached) yes
checking whether the gfortran linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking how to get verbose linking output from gfortran... -v
checking for Fortran 77 libraries of gfortran...  -L/usr/lib/gcc/x86_64-linux-gnu/4.6 -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../.. -lgfortran -lm -lquadmath
checking for dummy main to link with Fortran 77 libraries... none
checking for Fortran 77 name-mangling scheme... lower case, underscore, no extra underscore
checking if sgemm_ is being linked in already... no
checking for ATL_xerbla in -latlas... no
checking for sgemm_ in -lblas... yes
checking for dgemm_ in -ldgemm... no
checking for sgemm_ in -lmkl... no
checking for sgemm_ in -framework vecLib... no
checking for sgemm_ in -lcxml... no
checking for sgemm_ in -ldxml... no
checking for sgemm_ in -lscs... no
checking for sgemm_ in -lcomplib.sgimath... no
checking for sgemm_ in -lblas... (cached) yes
checking for sgemm_ in -lessl... no
checking for sgemm_ in -lblas... (cached) yes
checking for cheev_... no
checking for cheev_ in -llapack... yes
checking for MPI mode... checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating arpack.pc
config.status: creating Makefile
config.status: creating SRC/Makefile
config.status: creating UTIL/Makefile
config.status: creating TESTS/Makefile
config.status: creating EXAMPLES/Makefile
config.status: creating EXAMPLES/BAND/Makefile
config.status: creating EXAMPLES/COMPLEX/Makefile
config.status: creating EXAMPLES/NONSYM/Makefile
config.status: creating EXAMPLES/SIMPLE/Makefile
config.status: creating EXAMPLES/SVD/Makefile
config.status: creating EXAMPLES/SYM/Makefile
config.status: creating PARPACK/Makefile
config.status: creating PARPACK/SRC/Makefile
config.status: creating PARPACK/SRC/MPI/Makefile
config.status: creating PARPACK/UTIL/Makefile
config.status: creating PARPACK/UTIL/MPI/Makefile
config.status: creating PARPACK/UTIL/BLACS/Makefile
config.status: creating PARPACK/EXAMPLES/MPI/Makefile
config.status: creating PARPACK/EXAMPLES/BLACS/Makefile
config.status: creating PARPACK/SRC/BLACS/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
```

$make check
```
Making check in UTIL
make[1]: Entering directory `/home/f2/Documents/arpack-ng/UTIL'
make[1]: Nothing to be done for `check'.
make[1]: Leaving directory `/home/f2/Documents/arpack-ng/UTIL'
Making check in SRC
make[1]: Entering directory `/home/f2/Documents/arpack-ng/SRC'
make[1]: Nothing to be done for `check'.
make[1]: Leaving directory `/home/f2/Documents/arpack-ng/SRC'
Making check in .
make[1]: Entering directory `/home/f2/Documents/arpack-ng'
make[1]: Nothing to be done for `check-am'.
make[1]: Leaving directory `/home/f2/Documents/arpack-ng'
Making check in TESTS
make[1]: Entering directory `/home/f2/Documents/arpack-ng/TESTS'
make  dnsimp bug_1315_single bug_1315_double
make[2]: Entering directory `/home/f2/Documents/arpack-ng/TESTS'
make[2]: `dnsimp' is up to date.
make[2]: `bug_1315_single' is up to date.
make[2]: `bug_1315_double' is up to date.
make[2]: Leaving directory `/home/f2/Documents/arpack-ng/TESTS'
make  check-TESTS
make[2]: Entering directory `/home/f2/Documents/arpack-ng/TESTS'
make[3]: Entering directory `/home/f2/Documents/arpack-ng/TESTS'
PASS: dnsimp
PASS: bug_1315_single
FAIL: bug_1315_double
make[4]: Entering directory `/home/f2/Documents/arpack-ng/TESTS'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/home/f2/Documents/arpack-ng/TESTS'
============================================================================
Testsuite summary for arpack-ng 3.2.0
============================================================================
# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See TESTS/test-suite.log
Please report to https://github.com/opencollab/arpack-ng/issues/
============================================================================
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/home/f2/Documents/arpack-ng/TESTS'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/home/f2/Documents/arpack-ng/TESTS'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/f2/Documents/arpack-ng/TESTS'
make: *** [check-recursive] Error 1

===========================================
   arpack-ng 3.2.0: TESTS/test-suite.log
===========================================
# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: bug_1315_double
=====================
1000.000000
999.000000
997.000000
```

### LINKED ISSUE #17: arpack-ng 3.2.0 test failure on OS-X 10.10 w gfortran 5.1:  bug_1315_[single|double]
Steps to reproduce the problem:

```
./configure \
F77=/usr/local/bin/mpif77 \
--disable-dependency-tracking \
--prefix=/usr/local/Cellar/arpack/3.2.0/libexec \
--enable-mpi \
--with-blas="-L/usr/local/opt/veclibfort/lib -lvecLibFort"
make
make check
```

Result:
```
$ make check
Making check in UTIL
make[1]: Nothing to be done for `check'.
Making check in SRC
make[1]: Nothing to be done for `check'.
Making check in .
make[1]: Nothing to be done for `check-am'.
Making check in TESTS
/Applications/Xcode.app/Contents/Developer/usr/bin/make  dnsimp bug_1315_single bug_1315_double
/usr/local/bin/mpif77  -g -O2 -c -o dnsimp.o dnsimp.f
/usr/local/bin/mpif77  -g -O2 -c -o mmio.o mmio.f
/bin/sh ../libtool  --tag=F77   --mode=link /usr/local/bin/mpif77  -g -O2   -o dnsimp dnsimp.o mmio.o ../libarpack.la -L/usr/local/opt/veclibfort/lib -lvecLibFort
libtool: link: /usr/local/bin/mpif77 -g -O2 -o .libs/dnsimp dnsimp.o mmio.o  ../.libs/libarpack.dylib -L/usr/local/opt/veclibfort/lib -lvecLibFort
gcc -DPACKAGE_NAME=\"arpack-ng\" -DPACKAGE_TARNAME=\"arpack-ng\" -DPACKAGE_VERSION=\"3.2.0\" -DPACKAGE_STRING=\"arpack-ng\ 3.2.0\" -DPACKAGE_BUGREPORT=\"https://github.com/opencollab/arpack-ng/issues/\" -DPACKAGE_URL=\"\" -DPACKAGE=\"arpack-ng\" -DVERSION=\"3.2.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_BLAS=1 -DHAVE_LAPACK=1 -DHAVE_MPI=1 -I.     -g -O2 -c -o bug_1315_single.o bug_1315_single.c
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o bug_1315_single bug_1315_single.o ../libarpack.la -L/usr/local/opt/veclibfort/lib -lvecLibFort
libtool: link: gcc -g -O2 -o .libs/bug_1315_single bug_1315_single.o  ../.libs/libarpack.dylib -L/usr/local/opt/veclibfort/lib -lvecLibFort
gcc -DPACKAGE_NAME=\"arpack-ng\" -DPACKAGE_TARNAME=\"arpack-ng\" -DPACKAGE_VERSION=\"3.2.0\" -DPACKAGE_STRING=\"arpack-ng\ 3.2.0\" -DPACKAGE_BUGREPORT=\"https://github.com/opencollab/arpack-ng/issues/\" -DPACKAGE_URL=\"\" -DPACKAGE=\"arpack-ng\" -DVERSION=\"3.2.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_BLAS=1 -DHAVE_LAPACK=1 -DHAVE_MPI=1 -I.     -g -O2 -c -o bug_1315_double.o bug_1315_double.c
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o bug_1315_double bug_1315_double.o ../libarpack.la -L/usr/local/opt/veclibfort/lib -lvecLibFort
libtool: link: gcc -g -O2 -o .libs/bug_1315_double bug_1315_double.o  ../.libs/libarpack.dylib -L/usr/local/opt/veclibfort/lib -lvecLibFort
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: dnsimp
FAIL: bug_1315_single
FAIL: bug_1315_double
make[4]: Nothing to be done for `all'.
============================================================================
Testsuite summary for arpack-ng 3.2.0
============================================================================
# TOTAL: 3
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
```

and

```
===========================================
   arpack-ng 3.2.0: TESTS/test-suite.log
===========================================

# TOTAL: 3
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: bug_1315_single
=====================

999.997314
998.996887
997.997314
995.997131

FAIL: bug_1315_double
=====================

1000.000000
999.000000
997.000000
```

any ideas?

### PR DESCRIPTION
**Pull request by thrasibule**
Issue #3 was partially solved with pull request #2, by bringing back an older version of dlahqr.
However this only worked with reference blas, but with atlas or openblas, the issue persists as evidenced by #7, #16 and #17. This is another attempt at fixing it using a strategy suggested [here](http://forge.scilab.org/index.php/p/arpack-ng/issues/1315/#ic4079) by Marco Caliari.

This is an attempt to close #7 ,close #16  and close #17.

### CODE REVIEW

**Comment by sylvestre** [comment]
Impressive, could you also update the CHANGES to describe these changes? Thanks

**Comment by thrasibule** [comment]
added a description in the CHANGES file. All the credit for this idea goes to Marco Caliari, I just put the pull request together...

**Comment by caliarim** [comment]
Dear maintainers,

thanks for including my proposal in 3.3.0. In the old dlaqrb.f there was this piece of code

     if( wantt ) then
         i1 = 1
         i2 = n
         do 8 i=1,i2-2
            h(i1+i+1,i) = zero
 8       continue
      else
         do 9 i=1, ihi-ilo-1
            h(ilo+i+1,ilo+i-1) = zero
 9       continue
      end if

which is not present in dlahqr. Since dlaqrb.f was always called with wantt = .true., only the first branch is used. I don't know whether it is really necessary to zero out h. But it can be achived in dneigh.f by

   do 5 j = 1, n-2
         bounds(j) = zero
         workl(j+2+n*(j-1)) = zero
  5   continue 
      bounds(n-1) = zero
      bounds(n) = one
      call dlahqr(.true., .true., n, 1, n, workl, n, ritzr, ritzi, 1,
     &            1, bounds, 1, ierr)

**Comment by thrasibule** [comment]
@caliarim. If I understand the code correclty, this sets the entries on the second diagonal to be 0. h(i+2,i)=0 for 1<=i<=n-2. don't think this is needed. With the line:

```fortran
call dlacpy ('All', n, n, h, ldh, workl, n)
````
h is copied into workl which is an upper hessenberg matrix so all entries below the subdiagonal should be 0. What do you think?

**Comment by caliarim** [comment]
Look, for instance, at line 552 of dnaupd2. h(3,1) is used as storage.

**Comment by thrasibule** [comment]
Well spotted! However, in dlahqr code, I see:

```fortran
*     ==== clear out the trash ====
      DO 10 J = ILO, IHI - 3
         H( J+2, J ) = ZERO
         H( J+3, J ) = ZERO
   10 CONTINUE
```

So seems that it's already taken care of. Do you agree?

**Comment by caliarim** [comment]
Ah, right! This piece of code is not in dlahqr 2.0, and therefore it was inserted into dlaqrb. I agree with you that it is not necessary to zero out workl before calling dlahqr. To be 100% sure, I initialized  workl(j+2+n*(j-1)) with (-1.0d0)**j*1000.d0 and arpack worked without problems.

**Comment by thrasibule** [comment]
Cool! I'm glad this is sorted out.

**Pull request merged**
