### PR TITLE
Autoconf: add enable-atlas/openblas.

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

autotools: enhancement 

## Detailed changes proposed in this pull request

- add --enable-atlas
- add --enable-openblas

### CODE REVIEW

**Comment by fghoussen** [comment]
Not sure you wanna buy that !...

**Comment by sylvestre** [comment]
atlas is failing
and it would be nice to have cmake too
(and CHANGES updated)
i would take that :)

**Comment by fghoussen** [comment]
OK... Quite busy today: will be back on that tonight or tomorrow.
If I am not mistaken, the FindBLAS/LAPACK.cmake is supposed to already handle atlas/openblas/mkl according to what user wants.

**Comment by fghoussen** [comment]
quick look, no idea. @turboencabulator : any idea ?

**Comment by fghoussen** [comment]
@sylvestre: can't access logs of atlas job at my side in travis GUI ?! can you restart the job ?

**Comment by fghoussen** [comment]
logs are back (?!), but, no solution for now

**Comment by fghoussen** [comment]
dead ci ?!

**Comment by turboencabulator** [comment]
ax_blas.m4 handles the library search order, it's preferring openblas, then atlas, then several others.  It also lets you override it and specify which library you want, so you should be able to get this same effect without having to change the configure script. Something like `--with-blas=openblas` or `--with-blas=satlas`.  Not really sure about atlas since I think they've changed their library naming at some point.

With these changes it's going to be looking for particular pkgconfig files which might not even exist.  On my machine I have openblas.pc (not the blas-openblas.pc or lapack-openblas.pc that it's searching for).  I have a package of an earlier version of openblas that doesn't include any pkgconfig file, and my latest atlas package doesn't have one either.  Are these files Debian-isms that other distros won't have?

I'm thinking it would be better to document the appropriate `--with-blas` flags to make it work with your desired library rather than add new flags that may not work in all cases.  I assume CMake probably has some equivalent -D flag to do this?

**Comment by fghoussen** [comment]
> ax_blas.m4 handles the library search order, it's preferring openblas, then atlas, then several others. It also lets you override it and specify which library you want, 

Yes, I know (I use that in interface stage in travis.yml) !
... But I always felt like it's kind of cumbersome (or say not convienient).

> so you should be able to get this same effect without having to change the configure script.

Yes, if you are "expert enough" (means you know how to use pkg-config + how to pass that to ax_blas.m4 - lots of students I know don't ! :D)

> Something like --with-blas=openblas or --with-blas=satlas. Not really sure about atlas since I think they've changed their library naming at some point. With these changes it's going to be looking for particular pkgconfig files which might not even exist. 

No big deal (to me). If file is not found: do it by hand (even if it's not "so convenient")

> On my machine I have openblas.pc (not the blas-openblas.pc or lapack-openblas.pc that it's searching for). I have a package of an earlier version of openblas that doesn't include any pkgconfig file, and my latest atlas package doesn't have one either. Are these files Debian-isms that other distros won't have?

Do you have associated *-dev packages installed ? If yes, and, If pc file names change accross distro, this PR is likely meant to be closed !

> I'm thinking it would be better to document the appropriate --with-blas flags to make it work with your desired library rather than add new flags that may not work in all cases. I assume CMake probably has some equivalent -D flag to do this?

According to the doc (https://cmake.org/cmake/help/v3.13/module/FindBLAS.html), it seems that FindBLAS already handle customizing the search by setting stuffs like `set BLA_VENDOR=OpenBLAS` before running `cmake`... But from my unlucky experience, this is _not_ always working like people would expect it to work !

**Comment by fghoussen** [comment]
what if it's "just" a precision problem as we use atlas + simple precision arpack functions (s[ae]upd) ?

**Comment by fghoussen** [comment]
indeed, looks like a precision problem (after blas/lapack is replaced by atlas' ones).
double check is welcome !...

**Comment by fghoussen** [comment]
> On my machine I have openblas.pc (not the blas-openblas.pc or lapack-openblas.pc that it's searching for). I have a package of an earlier version of openblas that doesn't include any pkgconfig file, and my latest atlas package doesn't have one either

9c77ab2 may be a way to deal with that ?...

personal opinion: always prefer last updated versions + think "ahead" and use new arch/package (not target old-cray-or-archaic arch/package - the day you're stuck here: use ax_blas the "old" way specifying libs by hand...)

**Comment by fghoussen** [comment]
@turboencabulator , @sylvestre : what do you say ? is this worth ?

personal opinion: not "perfect" (what's perfect ?), but, convenient in many cases.

**Comment by fghoussen** [comment]
CI KO ! :D _Really_ not perfect !

**Comment by turboencabulator** [comment]
> Do you have associated *-dev packages installed ? If yes, and, If pc file names change accross distro, this PR is likely meant to be closed !

I'm building openblas and atlas packages from source.  No splitting out the -dev stuff into a separate package, no distro-specific additions.

openblas creates [openblas.pc](https://github.com/xianyi/OpenBLAS/blob/develop/openblas.pc.in) and Debian is [adding a few more](https://sources.debian.org/src/openblas/0.3.5+ds-1/debian/).
I can't find any pkgconfig files in the atlas 3.10.3 source, so Debian is [adding their own](https://sources.debian.org/src/atlas/3.10.3-7/debian/).

> [9c77ab2](https://github.com/opencollab/arpack-ng/commit/9c77ab2252f1006544387929c0b2083129157cd6) may be a way to deal with that ?...

Won't help.  The check will always fail if the pkgconfig file doesn't exist, or (with this change) exists but the version is too old.  This is a way to specify that earlier versions of openblas/atlas are not compatible with arpack.  Probably not what you were intending since I imagine they are compatible.

> personal opinion: always prefer last updated versions + think "ahead" and use new arch/package (not target old-cray-or-archaic arch/package - the day you're stuck here: use ax_blas the "old" way specifying libs by hand...)

FindBLAS and ax_blas.m4 are basically doing the same job, even the FindBLAS documentation says the search is based on acx_blas.m4.  The checks they are doing still have value over pkg-config, they make sure that the library is usable and contains the right symbols.

**Comment by fghoussen** [comment]
@turboencabulator : I agree with you !... So this PR may be closed-but-not-merged ? Too bad...

**Comment by fghoussen** [comment]
By the way, one may want to keep the precision fix from this PR anyway ?... I guess would be good.

**Comment by sylvestre** [comment]
So, what do we want to do it here? Closing?

**Comment by fghoussen** [comment]
> So, what do we want to do it here? Closing?

Yes closing... As pc files are provided by debian only. Unfortunately, no solution here...

You may want to keep the "precision fix" from this PR (with atlas, but not with openblas or blas/lapack, CI was failing because of precision problem related to ***s**[ae]upd) : not critical, but, if you want that, let me know, I'll open a new PR for that only.

I'am closing this as there is no solution for now (no pc files => no --enable options)

**Pull request closed without merging**
