### PR TITLE
arpackmm: add --dense option.

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

arpackmm: enhancement

## Detailed changes proposed in this pull request

allow support for dense matrices (for now, only sparse matrices are supported).

### CODE REVIEW

**Comment by fghoussen** [comment]
At my side, with debian/testing and eigen3.3.7-1 all is OK.
On CI, on old ubuntu with older eigen : compilation KO !
Not sure I can have time for that today. But likely I will look for a fix during the coming week.

**Comment by fghoussen** [comment]
Try to see if f5c5536 can fix compilation error occurring on CI (old ubuntu/eigen - OK on debian/testing).

**Comment by fghoussen** [comment]
Good news: CI OK. Coverage: not idea why reg is reported ?!...
@sylvestre : OK for you ? If so can you fixup + merge ?

**Comment by fghoussen** [comment]
62a655f does not seem to help coverage. CI OK.

**Comment by fghoussen** [comment]
Coverage reg: try to see if bff0d76 can help ? (add arpackmm.cpp)

**Comment by sylvestre** [comment]
Why the code coverage is decreasing?

**Comment by fghoussen** [comment]
> Why the code coverage is decreasing?

No idea ! I believe the coverage is biased in some way: can't figure out why !?

4151561 add only `arpackmm.cpp` in coverage which is (heavily !) covered by `arpackmm.sh` : you get a -6.9% coverage reg ?!... Without it (b7d6763) you get back to -0.4% which, here again, is biased as the code commited _is_ covered by `arpackmm` test but is not seen by coveralls !?

The coveralls report is not clear to me. Also, in this report you should see the EXAMPLES directory but it does not appear. Moreover, in the report (b7d6763) you see ICB/stat_icb.F90: [sc]statn_c are reported to be _not_ covered but they should as e70ecab call them explicitly !?

For me 4151461 should be keept but it comes with -6.9% reg which comes from outer space...

Giving up here

**Comment by fghoussen** [comment]
In the report, there are lots of files which seem to be filtered (but they shouldn't) : 

> make coveralls
> 
> Filter out unwanted GCOV files:
> 
> NO:  /home/fhoussen/Documents/arpack-ng/build/#home#fhoussen#Documents#arpack-ng#EXAMPLES#BAND#cnband.f.gcov
> NO:  /home/fhoussen/Documents/arpack-ng/build/#home#fhoussen#Documents#arpack-ng#EXAMPLES#BAND#cnbdr1.f.gcov

**Comment by fghoussen** [comment]
Seems coverage report is not triggered for d9a437d ... Boring...

**Comment by fghoussen** [comment]
To me, Coveralls*.cmake looks like a gaz factory to me... That seems to **not** support cpp (template).
1d9187d reduce the number of filtered files, but, you should see : 

> CMake Warning at /home/fhoussen/Documents/arpack-ng/cmake/CoverallsGenerateGcov.cmake:362 (message):
>  Failed to properly parse line (RES_COUNT = 1)
>  /home/fhoussen/Documents/arpack-ng/build/#home#fhoussen#Documents#arpack-ng#TESTS#icb_arpack_cpp.cpp.gcov:320
>  -->_Z24complex_symmetric_runnerIdEvv:

**Comment by fghoussen** [comment]
CI seems to not report error I have on my laptop ? Not sure if this is because of ` > /dev/null `... less files seems to have been filtered, but, coverage hook is down (no report created).

**Comment by fghoussen** [comment]
coverage report still not reported ?!...

**Comment by fghoussen** [comment]
> coverage report still not reported ?!...

{"message":"JSON file not found or failed to parse.","error":true,"url":""}Built target coveralls_upload

**Comment by fghoussen** [comment]
Even worse ?!....

More file filtered, and, no report triggered back from travis to coveralls

> Built target coveralls_generate
> Scanning dependencies of target coveralls_upload
> Uploading coveralls output...
> % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                 Dload  Upload   Total   Spent    Left  Speed
>
>  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100  726k  100    75  100  726k    180  1750k --:--:-- --:--:-- --:--:-- 1754k
> {"message":"JSON file not found or failed to parse.","error":true,"url":""}Built target coveralls_upload

**Comment by fghoussen** [comment]
Still broken ?!... 

CI has errors of the type I see on my laptop : 

> Generate JSON for file: SRC/zstatn.f...
> MD5: /home/travis/build/opencollab/arpack-ng/TESTS/bug_1323.f = 688b61ecdcf556d612fc9d45e3df450d
> CMake Warning at /home/travis/build/opencollab/arpack-ng/cmake/CoverallsGenerateGcov.cmake:362 (message):
>   Failed to properly parse line (RES_COUNT = 1)
>  /home/travis/build/opencollab/arpack-ng/build/#home#travis#build#opencollab#arpack-ng#TESTS#bug_1323.f.gcov:28
>  -->.  Canot -- IRISA/CNRS -- Edouard.Canot@irisa.fr
> 437 of 436 lines read!
> Generate JSON for file: TESTS/bug_1323.f...

I guess from here all reminding files are not processed : you get more unfiltered files than previously.... And always the same error in the end : 

> {"message":"JSON file not found or failed to parse.","error":true,"url":""}Built target coveralls_upload

which means : no coverage report will be created

**Comment by sylvestre** [comment]
you should dump the content of the json to see what is inside

**Comment by fghoussen** [comment]
JP Coffe may conclude now...

**Comment by fghoussen** [comment]
Opening an issue https://github.com/JoakimSoderberg/coveralls-cmake ? get some feedback ?

**Comment by fghoussen** [comment]
Dev is stuck by coverage: not fair... No solution at coverage side.
What about splitting this PR in 3 : 1 for the dev, 1 for the cmake rewrite (?), 1 for coverage ?
Or do you prefer to finish this one PR to the end ? (no more idea to test)

**Comment by fghoussen** [comment]
wft  ?!... In coveralls, now you see EXAMPLES AND PARPACK (not present before) but still get coverage reg

**Comment by fghoussen** [comment]
@sylvestre : do you buy b3e758c ? (small) coverage reg <=> more file covered

**Comment by fghoussen** [comment]
https://github.com/JoakimSoderberg/coveralls-cmake/issues/23....

**Comment by fghoussen** [comment]
For clarity, splitting this in 2 independent parts: the 2d part is #201

**Pull request merged**
