### PR TITLE
Fix a potential deadlock when using custom communicators (Fix issue #46)

### PR DESCRIPTION
**Pull request by iskakoff**
Possible solution for https://github.com/opencollab/arpack-ng/issues/46

remove variable `first` from `p*aitr` and `p*apps`, create two  `common` variables `apps_first` and `aitr_first`. Each time when `p*aupd` is called for a first time (`ido .eq. 0`) set variables `*_first` to `.true.` then they will be updated in `p*aitr` and `p*apps`.

### CODE REVIEW

**Comment by sylvestre** [comment]
Could you add a test which demonstrates the issue you are addressing? (to make sure we don't regress) 
Thanks
(and also update CHANGES)

**Comment by iskakoff** [comment]
Ok, will add test soon.

**Comment by sylvestre** [comment]
Thanks!

**Comment by sylvestre** [comment]
With an update of CHANGES too, we will be perfect. Thanks again!

**Comment by iskakoff** [comment]
Done

**Pull request merged**
