### PR TITLE
[TravisCI] travis_debian.sh: test BP/ILP64 on debian-based arch.

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

[TravisCI] Integrate ILP64 in travis_ubuntu.sh.

### CODE REVIEW

**Comment by fghoussen** [comment]
@caliarim : bug_142 fails on ubuntu focal + ILP64, ring a bell ? (the third KO should be fixed if reducing nev)

> FAIL: bug_142
 STOP 1
  Error with _naupd, info =                    -8
  Check the documentation of _naupd
FAIL bug_142 (exit status: 1)
FAIL: bug_142_gen
STOP 1
  Error with _naupd, info =                    -8
  Check the documentation of _naupd
FAIL bug_142_gen (exit status: 1)

**Comment by fghoussen** [comment]
May be related https://git.slaanesh.org/killruana/nextpnr/commit/6e932f5a2db83bece51f744ed59c42a0f7377b6f : if so the problem seems to be embedded in boost, wait 1.74 to be fixed ?

> sed '5q;d' /usr/local/lib/cmake/BoostDetectToolset-1.72.0.cmake
> string(REGEX MATCHALL "[0-9]+" _BOOST_COMPILER_VERSION ${CMAKE_CXX_COMPILER_VERSION})

**Comment by fghoussen** [comment]
Was this merged in master ?!... This was broken and should not have been merged.
I kept that in view to find a solution some day... But not yet ready !

**Comment by fghoussen** [comment]
OK, not merged into master. Got blurred by the star-wars history !... Pushed force: not sure this is ready yet

**Comment by sylvestre** [comment]
ok, cool :+1: 

I would like to do a release today or tomorrow, is it ok with you?

**Comment by fghoussen** [comment]
OK for me, would be great... But looks like there is a reg on CI : osx fails, does not find mpi ?! see #285

**Comment by fghoussen** [comment]
No merge : will likely break unless unexpected lucky surprise

**Comment by fghoussen** [comment]
@sylvestre : still broken, should I drop this ? Or you prefer to keep it in case it could work someday ?

**Comment by fghoussen** [comment]
docker images may be slow : I guess that's why openmpi freeze (multi proc/thread overflowed ?)... Trying with `travis_wait`

**Comment by fghoussen** [comment]
@sylvestre : do you want to keep or kill debian build ? Or try using testing instead of stable ?

ubuntu/focal tests all features : regular (no boost, no ILP64), boost-python, ILP64 => should be all clear here.

debian docker box(bb29598)  has consistent problems :  I guess mpi version is to blame here (freeze, crash).
On debian, CI is OK but triggers this msg which sounds like underneath hidden problem (you may or not have on testing):
> [016752d6c9fc:22435] 1 more process has sent help message help-mpi-btl-base.txt / btl:no-nics
> [016752d6c9fc:22435] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

Easy solution : kill debian if focal can do all the jobs. Better solution: try to keep at least one debian job. This is your decision : let me know what you prefer.

**Comment by fghoussen** [comment]
> ubuntu/focal tests all features : regular (no boost, no ILP64), boost-python, ILP64 => should be all clear here.

Turns out there are boring problems here too... seems `make check` on last focal ILP64 build does not understand that it needs to use both ILP64 BLAS *and* LAPACK : it uses ILP64 BLAS with regular LAPACK....

**Comment by fghoussen** [comment]
1441270: nothing was done (just debugging with prints) but warning msg on debian disappeared ?!?!...
Tricky to get one script for several distro : each change that make work something here, break something else elsewhere.

**Comment by fghoussen** [comment]
Now on stretch ?!...
> [ 26%] Building Fortran object CMakeFiles/parpack.dir/PARPACK/SRC/MPI/pcgetv0.f.o
> /usr/bin/gfortran   -I/tmp/arpack-ng/build -I/tmp/arpack-ng  -O3 -DNDEBUG -O3   -c /tmp/arpack-ng/PARPACK/SRC/MPI/pcgetv0.f -o CMakeFiles/parpack.dir/PARPACK/SRC/MPI/pcgetv0.f.o
>/tmp/arpack-ng/PARPACK/SRC/MPI/pcgetv0.f:131: Error: Can't open included file 'mpif.h'

**Comment by fghoussen** [comment]
Debian build breaks but pass green ?!...

>The following tests FAILED:
>	 72 - pcndrv1_ex (Failed)
>	 73 - pdndrv1_ex (Failed)
>	 74 - pdndrv3_ex (Failed)
>	 75 - pdsdrv1_ex (Failed)

**Comment by fghoussen** [comment]
Do not merge this ?!

Debian and focal builds pass but fail this way

>The following tests FAILED:
	 72 - pcndrv1_ex (Failed)
	 73 - pdndrv1_ex (Failed)
	 74 - pdndrv3_ex (Failed)
	 75 - pdsdrv1_ex (Failed)
	 76 - psndrv1_ex (Failed)
	 77 - psndrv3_ex (Failed)
	 78 - pssdrv1_ex (Failed)
	 79 - pzndrv1_ex (Failed)
	 90 - icb_parpack_c_tst (Failed)
	 91 - icb_parpack_cpp_tst (Failed)
Errors while running CTest
Makefile:138: recipe for target 'test' failed
make: *** [test] Error 8
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.
Process 1 ([[13792,1],1]) is on host: 20ef3166c84a
Process 2 ([[13792,1],0]) is on host: 20ef3166c84a
BTLs attempted: self
Your MPI job is now going to abort; sorry.
An error occurred in MPI_Init
on a NULL communicator
MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
and potentially your MPI job)
--------------------------------------------------------------------------

**Comment by fghoussen** [comment]
on debian, MPI seems to break (or not) _some_ times : seems to be non reproducible...

**Comment by fghoussen** [comment]
`issue46.f` coming from #46 triggers type mismatch if ILP64 is enabled: @iskakoff can you check 01e4f58 still covers issue 46 but hopefully without crashing ILP64 ?... For me only MPI communicator changes, `myid` and `nprocs` stay the same.

**Comment by fghoussen** [comment]
Yet another stupid endless problem... ILP64 seems to need MPI to provide ISO C BINDING (`mpi_f08`) :
- Compiling with INTERFACE64 means you need to have control on integer type.
- If MPI is also required, then MPI types must be consistent with ILP64: to make sure of this, we must use the ISO_C_BINDING API provided by MPI.

**Comment by fghoussen** [comment]
Lots of inter-connected problems mixing at the same time...

**Comment by fghoussen** [comment]
Give up after move to github actions.

**Pull request closed without merging**
