### PR TITLE
Change the continuation line format for stat.h, debug.h

### LINKED ISSUE #300: Too long lines for flang
Arpack does not compile with AMD's llvm based flang compiler. 

Cmake gives the reason

```
CMake Warning at CMakeLists.txt:163 (message):
   build script does not know how to enable your Fortran compiler's
   preprocessor and support for lines longer than 72 characters: set them
   manually via FFLAGS.
 -- Configuration summary for arpack-ng-3.9.0:
    -- prefix: /usr/local
    -- MPI: OFF
    -- ICB: OFF
    -- INTERFACE64: 0
    -- FC:      /opt/AMD/aocc-compiler-3.0.0/bin/flang
    -- FCFLAGS: -O3 -DNDEBUG
    -- BLAS:
       -- link:    /usr/lib/x86_64-linux-gnu/libblas.so
    -- LAPACK:
       -- link:    /usr/lib/x86_64-linux-gnu/liblapack.so
       -- link:    /usr/lib/x86_64-linux-gnu/libblas.so
```

The error message is then

```
[  1%] Building Fortran object CMakeFiles/arpack.dir/UTIL/icnteq.f.o
[  2%] Building Fortran object CMakeFiles/arpack.dir/UTIL/icopy.f.o
[  3%] Building Fortran object CMakeFiles/arpack.dir/UTIL/iset.f.o
[  4%] Building Fortran object CMakeFiles/arpack.dir/UTIL/iswap.f.o
[  5%] Building Fortran object CMakeFiles/arpack.dir/UTIL/ivout.f.o
[  6%] Building Fortran object CMakeFiles/arpack.dir/UTIL/second_NONE.f.o
[  7%] Building Fortran object CMakeFiles/arpack.dir/UTIL/svout.f.o
[  8%] Building Fortran object CMakeFiles/arpack.dir/UTIL/smout.f.o
[  9%] Building Fortran object CMakeFiles/arpack.dir/UTIL/dvout.f.o
[ 10%] Building Fortran object CMakeFiles/arpack.dir/UTIL/dmout.f.o
[ 11%] Building Fortran object CMakeFiles/arpack.dir/UTIL/cvout.f.o
[ 12%] Building Fortran object CMakeFiles/arpack.dir/UTIL/cmout.f.o
[ 13%] Building Fortran object CMakeFiles/arpack.dir/UTIL/zvout.f.o
[ 14%] Building Fortran object CMakeFiles/arpack.dir/UTIL/zmout.f.o
[ 15%] Building Fortran object CMakeFiles/arpack.dir/SRC/cgetv0.f.o
F90-S-0034-Syntax error at or near & (/home/fwein/code/arpack-ng-master/debug.h: 8)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/debug.h: 9)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/debug.h: 10)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/debug.h: 11)
F90-S-0034-Syntax error at or near & (/home/fwein/code/arpack-ng-master/debug.h: 12)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/debug.h: 13)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/debug.h: 14)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/debug.h: 15)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/debug.h: 16)
F90-S-0034-Syntax error at or near end of line (/home/fwein/code/arpack-ng-master/stat.h: 12)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/stat.h: 13)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/stat.h: 14)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/stat.h: 15)
F90-S-0034-Syntax error at or near end of line (/home/fwein/code/arpack-ng-master/stat.h: 16)
F90-S-0034-Syntax error at or near identifier px (/home/fwein/code/arpack-ng-master/stat.h: 17)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/stat.h: 18)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/stat.h: 19)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/stat.h: 20)
F90-S-0034-Syntax error at or near , (/home/fwein/code/arpack-ng-master/stat.h: 21)
  0 inform,   0 warnings,  19 severes, 0 fatal for cgetv0
```

I guess adding the flag would help, I just didn't find it yet.

### PR DESCRIPTION
**Pull request by payerle**
AOCC flang compiler is complaining about the continuation lines in these
two files.  It does not complain about similar continuation lines in
files (e.g. SRC/icbacn.F90), so I believe this is due to flang setting
the Fortran dialect to something like F77 for most of the compilations,
which cause problems with these *.h files.

I cannot find a way to force flang Fortran dialect to accept the & at
end of line continuation marker, so this patch changes the continuation
lines in these two files (stat.h, debug.h) to use continuation marker in
column 6.

This should fix #300

## Pull request purpose

fixing issue #xx ? enhancement ? new feature ?...

## Detailed changes proposed in this pull request

-
-
-

### CODE REVIEW

**Comment by fghoussen** [comment]
CI's back. Can you rebase?

**Comment by sylvestre** [comment]
I enabled the github option for this:
image

**Comment by fghoussen** [comment]
@payerle: can you have a look? [😱]()

**Comment by sylvestre** [comment]
glad we have the CI back, well done ;)

**Pull request merged**
