### PR TITLE
Make building tests an option in CMake

### PR DESCRIPTION
**Pull request by FabienPean**
Tests were built by default with CMake, it is now an option set to ON by default to preserve previous behavior.

### CODE REVIEW

**Comment by fghoussen** [comment]
Can you put the previous code into a cmake function and call that function if the option is ON

**Comment by FabienPean** [comment]
Is that the change you meant (should the function be defined there) ? It looks a bit weird, did you mean refactor the previous code to follow the "Examples" part of the CMakeLists instead ?

**Comment by fghoussen** [comment]
Would be good to have equivalent of `function(examples list_name)` and `function(pexamples list_name)` but not sure if this can be easy done for all tests.

**Comment by FabienPean** [comment]
```cpp
    enable_testing()
    set(CMAKE_CTEST_COMMAND ctest -V)   
```

had to be moved in global scope of the script because the CMake function creates a new scope. To keep it fully apart, it should be using the  `macro/endmacro` couple instead of the `function/endfunction`.

Now with regard to the CI, for the failing job `macos_latest_cmake_python`, it looks like a problem resulting from the transition to macOS 12.

**Comment by fghoussen** [comment]
CI seems broken for other reasons: we'll have to fix it in a dedicated PR before merging this.

**Pull request merged**
