### PR TITLE
arpackmm: add --slvItrPC option (PC: Jacobi, ILU).

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

arpackmm: enhancement

## Detailed changes proposed in this pull request

add control on preconditioners if iterative solvers are needed.

### CODE REVIEW

**Comment by sylvestre** [comment]
please update the CHANGES file

**Comment by fghoussen** [comment]
done

**Comment by fghoussen** [comment]
OK... Quite busy today: will be back on that tonight or tomorrow.
Will have to test a slight modif here too + update CHANGES file.

**Comment by fghoussen** [comment]
quick test for small improvement

**Comment by fghoussen** [comment]
should be good to go !

**Pull request merged**
