### PR TITLE
Remove appended _c and update comments

### PR DESCRIPTION
**Pull request by dbeurle**
Per review.  Formatting changes to match Google format.

### CODE REVIEW

**Comment by dbeurle** [comment]
After this I've got everything done you can finally release ^_^

**Comment by fghoussen** [comment]
What about parpack ?

**Comment by dbeurle** [comment]
Is it all working?  The same patterns should apply.

**Comment by fghoussen** [comment]
For symmetry, would be good you do the job for parapck too

**Comment by sylvestre** [comment]
Indeed, @dbeurle could you do that? Thanks :)

**Comment by dbeurle** [comment]
I can - it'll have to be tonight since unfortunately I don't get paid to write code :-(

**Pull request merged**
