### PR TITLE
[BUG FIX] Fix install: headers in /path/to/local/include/arpack

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

fixing issue #394

### CODE REVIEW

**Comment by fghoussen** [comment]
Tests which test installation are broken!

**Comment by sylvestre** [comment]
headers still get installed in:
debian/tmp/usr/include/arpack-ng/

**Comment by fghoussen** [comment]
Should be OK

**Comment by sylvestre** [comment]
Closer ! these files are still installed in arpack-ng

debian/tmp/usr/include/arpack-ng/arpack.h     debian/tmp/usr/include/arpack-ng/parpack.h
debian/tmp/usr/include/arpack-ng/arpack.hpp   debian/tmp/usr/include/arpack-ng/parpack.hpp
debian/tmp/usr/include/arpack-ng/debug_c.h    debian/tmp/usr/include/arpack-ng/stat_c.h
debian/tmp/usr/include/arpack-ng/debug_c.hpp  debian/tmp/usr/include/arpack-ng/stat_c.hpp

**Comment by fghoussen** [comment]
I'll have a look. Do you want to suppress the current 3.9.0 tag on master + fix this + retag 3.9.0, or, create a new tag when this is fixed?

**Comment by fghoussen** [comment]
> Closer ! these files are still installed in arpack-ng
> 
> debian/tmp/usr/include/arpack-ng/arpack.h debian/tmp/usr/include/arpack-ng/parpack.h debian/tmp/usr/include/arpack-ng/arpack.hpp debian/tmp/usr/include/arpack-ng/parpack.hpp debian/tmp/usr/include/arpack-ng/debug_c.h debian/tmp/usr/include/arpack-ng/stat_c.h debian/tmp/usr/include/arpack-ng/debug_c.hpp debian/tmp/usr/include/arpack-ng/stat_c.hpp

CI didn't see this because the installation tests do not test C/C++ binding as far as I remember.
Would be good to improve this in the future

**Comment by sylvestre** [comment]
3.9.0 has been tagged, we should do 3.9.1 now :)

**Comment by fghoussen** [comment]
@sylvestre: if OK at your side, fix-up and merge

**Comment by 3rav** [comment]
On the occasion of the 3.9.1 release, I have a bug for 3.9.0 with the `-DICBEXMM=ON` flag in the mingw32bit (only 32bit) environment:

```
 [221/222] Building CXX object CMakeFiles/arpackmm.dir/EXAMPLES/MATRIX_MARKET/arpackmm.cpp.obj
  FAILED: CMakeFiles/arpackmm.dir/EXAMPLES/MATRIX_MARKET/arpackmm.cpp.obj 
  D:\M\msys64\mingw32\bin\g++.exe  -IC:/_/B/src/build-MINGW32-static-32 -IC:/_/B/src/arpack-ng-3.9.0 -IC:/_/B/src/arpack-ng-3.9.0/ICB -ID:/M/msys64/mingw32/include/eigen3 -O3 -DNDEBUG -std=gnu++11 -MD -MT CMakeFiles/arpackmm.dir/EXAMPLES/MATRIX_MARKET/arpackmm.cpp.obj -MF CMakeFiles\arpackmm.dir\EXAMPLES\MATRIX_MARKET\arpackmm.cpp.obj.d -o CMakeFiles/arpackmm.dir/EXAMPLES/MATRIX_MARKET/arpackmm.cpp.obj -c C:/_/B/src/arpack-ng-3.9.0/EXAMPLES/MATRIX_MARKET/arpackmm.cpp
  
  
  cc1plus.exe: out of memory allocating 8392703 bytes
```

**Comment by fghoussen** [comment]
> On the occasion of the 3.9.1 release, I have a bug for 3.9.0 with the `-DICBEXMM=ON` flag in the mingw32bit (only 32bit) environment:
> 
> ```
>  [221/222] Building CXX object CMakeFiles/arpackmm.dir/EXAMPLES/MATRIX_MARKET/arpackmm.cpp.obj
>   FAILED: CMakeFiles/arpackmm.dir/EXAMPLES/MATRIX_MARKET/arpackmm.cpp.obj 
>   D:\M\msys64\mingw32\bin\g++.exe  -IC:/_/B/src/build-MINGW32-static-32 -IC:/_/B/src/arpack-ng-3.9.0 -IC:/_/B/src/arpack-ng-3.9.0/ICB -ID:/M/msys64/mingw32/include/eigen3 -O3 -DNDEBUG -std=gnu++11 -MD -MT CMakeFiles/arpackmm.dir/EXAMPLES/MATRIX_MARKET/arpackmm.cpp.obj -MF CMakeFiles\arpackmm.dir\EXAMPLES\MATRIX_MARKET\arpackmm.cpp.obj.d -o CMakeFiles/arpackmm.dir/EXAMPLES/MATRIX_MARKET/arpackmm.cpp.obj -c C:/_/B/src/arpack-ng-3.9.0/EXAMPLES/MATRIX_MARKET/arpackmm.cpp
>   
>   
>   cc1plus.exe: out of memory allocating 8392703 bytes
> ```

Please, avoid mixing different problems: this is not connected to installation problems.
But likely duplicate of #289 : C++ templates are handy but come with big memory requirements (which make build time increase), AFAIK there is nothing to do against this

**Pull request merged**
