### PR TITLE
CI based on GitHub Actions only

### PR DESCRIPTION
**Pull request by dimpase**
## Travis CI no longer viable

here we replace Travis CI with GitHub Actions CI

-
-

### CODE REVIEW

**Comment by dimpase** [comment]
I just ran this here: https://github.com/dimpase/arpack-ng/actions/runs/1279477662

Something wrong with Docker-based runs (the rest are good), but Docker is a bit above my pay grade...

**Comment by dimpase** [comment]
Perhaps we should disable Docker stuff for the time being, after all, it's pretty much orthogonal to the project aim.

**Comment by fghoussen** [comment]
> Perhaps we should disable Docker

No ! Docker is precious : it enables to run other distros (fedora, centos, ...) from anywhere (ubuntu in this case).
Docker works if you set up secrets (what I did for my account and opencollab - that's its OK there but KO at your side) : once merged all PRs should run OK (at opencollab side)

**Comment by dimpase** [comment]
well, then you can go ahead and merge this, right?

**Comment by sylvestre** [comment]
I think the docker solution is pretty heavy and you have now better solution in github actions, for example:
https://github.com/opencollab/llvm-toolchain-integration-test-suite/commit/d3dec7f909531936678d4e6698413bf4c426dd43

**Comment by sylvestre** [comment]
let's try to see if it sticks :)

**Comment by dimpase** [comment]
It worked! https://github.com/opencollab/arpack-ng/actions/runs/1285891897 is all green.

**Comment by fghoussen** [comment]
So we don't have coverage anymore : clean coveralls (cmake files / options) ?

**Comment by dimpase** [comment]
Oops, mea culpa. I didn't notice that you only have

```
on: [push]
```

an not

```
on: [push, pull_request]
```

which prevented triggering Actions for PRs.

I'll fix this later tonight.

**Comment by dimpase** [comment]
see, now on #322 all the GitHub Actions available are triggered.

**Pull request merged**
