### PR TITLE
[CMake] Use targets following "modern CMake".

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

fixing issue #281 ?

### CODE REVIEW

**Comment by fghoussen** [comment]
Oops, forgot to use targets (in place of libs) as you may have seen !... :D

**Comment by fghoussen** [comment]
Oh men ! Targets are created by Find*.cmake only if cmake version >= 3.18 !... Missed that.
Quick fix to create them in this case : not sure this could be OK with old cmake version, CI will tell us.

**Comment by Fabian188** [comment]
How can I test this? I don't find the branch in my cloned repository.
I want to test it on a ubuntu without BLAS/LAPACK to build libarpack only.

**Comment by fghoussen** [comment]
Clone (or add a remote) to my repo (from where the PR comes) : https://github.com/fghoussen/arpack-ng.
Then, checkout the PR branch : issue281

**Comment by Fabian188** [comment]
I tested issue281. It works on a system with blas/lapack installed, but not on a system where blas/lapack is not installed:
```
: cmake ..
-- The C compiler identification is GNU 7.5.0
-- The Fortran compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
-- Verifying Fortran/C Compiler Compatibility
-- Verifying Fortran/C Compiler Compatibility - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake-3.10/Modules/FindBLAS.cmake:699 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  CMakeLists.txt:199 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/parallels/tmp/arpack-ng/build/CMakeFiles/CMakeOutput.log".
See also "/home/parallels/tmp/arpack-ng/build/CMakeFiles/CMakeError.log".

```

**Comment by fghoussen** [comment]
Totally expected ! You must set BLAS/LAPACK targets _if not already set_ (will be native if cmake is "new enough").

The idea "Modern CMake" wants you to follow looks like :
```
find_package(A) # set A target.
find_package(B) # where B needs A: set B target, use A target.
``` 

Now in real life you have (at least ?) 3 situations : 

case 1: you have "new enough" cmake that ships already find_package with targets. You have nothing to do:
```
find_package(A)
find_package(B) # where B needs A.
``` 

case 2: you have a "old" cmake that is not yet "modern", so again (https://github.com/opencollab/arpack-ng/pull/282#issuecomment-672264427 @Fabian188) you need to set the target at your side waiting for new cmake:
```
find_package(A)
if (NOT TARGET A)
  add_library(MPI::MPI_Fortran INTERFACE IMPORTED)
  set_target_properties(A::A PROPERTIES INTERFACE_LINK_LIBRARIES "${A_LIBRARIES}")
endif()
find_package(B) # where B needs A.
``` 

case 3 : you have no find_package, so you use `option` (to pass A_LIBRARIES at cmake command line), so you need to set the target at your side here too:
```
option(A "Pass A libraries at the command line : cmake -D A=/path/to/A.so")
if (NOT TARGET A)
  add_library(MPI::MPI_Fortran INTERFACE IMPORTED)
  set_target_properties(A::A PROPERTIES INTERFACE_LINK_LIBRARIES "${A_LIBRARIES}")
endif()
find_package(B) # where B needs A.
```

**Comment by fghoussen** [comment]
BTW, I didn't impact (lazy, no time) eigen and boost : they are templates.
Targets are really needed to binaries lib consistency (mpi, blas, lapack).

**Pull request merged**
