### PR TITLE
arpackmm: add --slvDrtPvtThd option.

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

arpackmm: enhancement

## Detailed changes proposed in this pull request

add control on pivot threshold if direct solver is used.

### CODE REVIEW

**Comment by fghoussen** [comment]
Should not increase coverage ! :D 
I will likely PR another small feature by the end of the day or tomorrow : after that 3.7 should be OK (1st "good" enough version of arpackmm - probably add more for versions > 3.7 as I will need it).

**Comment by fghoussen** [comment]
Oh... Stupid : make_unique is likely C++14 ? And compiler option is C++11.
Should I move to C++14 ? Or modify the code to compile with C++11 ?
Any suggestion to bypass this stupid thing is welcome !...

**Comment by sylvestre** [comment]
C++14 is a bit too early :/ (I know)

**Comment by fghoussen** [comment]
@sylvestre : turns out to be OK ! Do you take it ?

**Comment by sylvestre** [comment]
Sorry, no, I don't want to have C++14 as mandatory dep yet.

**Comment by sylvestre** [comment]
Sorry about that, please reopen

**Comment by fghoussen** [comment]
> Sorry, no, I don't want to have C++14 as mandatory dep yet.

OK, got it. I'll rewrite it with C++11.

> Sorry about that, please reopen

OK. For master, consider reset --hard HEAD~2 ?... As you like.
Seems I can't reopen a merged PR. I'll create a new PR for this.

**Comment by sylvestre** [comment]
Done, thanks

**Comment by fghoussen** [comment]
> Done, thanks

OK, I'll PR back again quite soon !

**Pull request merged**
