### PR TITLE
Arpackmm: add --schur option.

### PR DESCRIPTION
**Pull request by fghoussen**
## Pull request purpose

arpackmm: enhancement.

## Detailed changes proposed in this pull request

Enable to compute ritz or schur vectors.

### CODE REVIEW

**Comment by sylvestre** [comment]
Is it possible to have something less cryptic ? slvDrtPvtThd

**Comment by fghoussen** [comment]
This is based on #180 + coverage is likely to increase.
That's all I got for arpack-3.7 !

**Comment by fghoussen** [comment]
> Is it possible to have something less cryptic ? slvDrtPvtThd

What do you propose ?

Lots of options already around ! To know what they deal with prefix are added up

```
~> ./arpackmm --help
Usage: running arpack to check for eigen values/vectors.
...
  --slv S:          solver (BiCG, CG, LU)
                      BiCG: iterative method, any matrices
                        CG: iterative method, sym matrices only
                        LU:    direct method, any matrices
                        QR:    direct method, any matrices
                    default: BiCG
  --slvItrTol T:    solver tolerance T (for iterative solvers).
                    default: eigen default value
  --slvItrMaxIt M:  solver maximum iterations M (for iterative solvers).
                    default: eigen default value
  --slvDrtPvtThd T: solver pivot threshold T (for direct solvers).
                    default: eigen default value

```

pivot threshold only apply to direct (Drt) solver.
tol / max it only apply to iterative solver (Itr).

Probably more options to go when in version > 3.7, I'll had to add preconditioner (which make sense only with iterative solver : so you probably could expet a --slvItrPC)

**Comment by fghoussen** [comment]
rebased. no coverage increase: too bad !

**Pull request merged**
