### PR TITLE
Add clang-format

### PR DESCRIPTION
**Pull request by dbeurle**
(Optional) add clang-format for consistent formatting

### CODE REVIEW

**Comment by sylvestre** [comment]
great idea!
just a comment, I would prefer using a well defined coding style like Google's, could you please change that?

**Comment by dbeurle** [comment]
Absolutely - I put the google style in.  Do you know of a way to get CI to make sure this is correct / do the formatting on commit?  Just in case a dev doesn't have clang-format installed locally.

**Comment by sylvestre** [comment]
`BasedOnStyle: Google`
Just that should be enough, don't you think?

**Comment by dbeurle** [comment]
Something new every day.  I did `clang-format -style=google -dump-config > .clang-format`.  Can you squash these commits on merge?

**Pull request merged**
