### PR TITLE
ILP64 support

### PR DESCRIPTION
**Pull request by nalimilan**
Cf. https://github.com/opencollab/arpack-ng/issues/30

### CODE REVIEW

**Comment by sylvestre** [comment]
The build is failing with this change, could you have a look?
By the way, are you also planning to update the cmake build? Thanks

**Comment by nalimilan** [comment]
The build failure looks like I missed a substitution in the Makefiles somewhere, but I need to find where. I hadn't tested PARPACK correctly.

I'll take care of CMake if you agree with the general strategy.

**Comment by sylvestre** [comment]
Looks great. Could you just add some automation and testing about this in travis?
https://github.com/opencollab/arpack-ng/blob/master/.travis.yml

Maybe a new build with ILP64 and the tests.

**Comment by nalimilan** [comment]
It would be nice, but we need an ILP64 BLAS with suffix to test this, and I don't think Debian/Ubuntu has packages for that...

**Comment by sylvestre** [comment]
too bad. A solution would be to build also blas in travis but this might be overkill

**Comment by nalimilan** [comment]
OK, I found the bug, and now it looks good.

That said, the tests fail with ILP64 (this also happens in the Julia tree). Correct output with LP64:
```
$ TESTS/bug_1315_double 
1000.000000
999.000000
998.000000
997.000000
996.000000
995.000000
994.000000
993.000000
992.000000
```
Incorrect output with ILP64:
```
$ deps/build/arpack-ng-3.2.0/TESTS/bug_1315_double 
1000.000000
999.000000
998.000000
997.000000
995.000000
```
I suspect this is because of the tolerance. Could you suggest a fix? Could be left for another PR though, as it isn't strictly related to the present set of changes.

Finally, I've left a FIXME regarding the way to set the Fortan integer size. How could I adapt the argument depending on the compiler?

**Comment by nalimilan** [comment]
Actually, I've found a way to increase portability (see the last commit).

**Comment by sylvestre** [comment]
I merged another PR which conflict with yours, could you rebase it? Sorry about that :/

**Comment by sylvestre** [comment]
Btw, are you planning to update the cmake build here?

**Comment by sylvestre** [comment]
Also, please update the changelog with your changes

**Comment by nalimilan** [comment]
Will do. I'm currently looking at how to get this to work with CMake. One of the issues is that I haven't found a way to apply the Fortran name mangling from the CMake scripts: the only supported way seems to be to create a C header file. This in turns means that 1) the header must be created even when not adding a suffix, and 2) that I need to adapt the Makefiles too.

**Comment by nalimilan** [comment]
I've pushed another commit with CMake support. Everything looks fine, but I couldn't fully test it because AFAICT I can't specify a custom BLAS.

There's also the tests failure mentioned at https://github.com/opencollab/arpack-ng/pull/32#issuecomment-172224682. Any pointers?

@tkelman @stevengj Can you confirm that this would be OK for Julia? In particular, `OPENBLAS_SYMBOLSUFFIX=64_` will have to be translated to `SYMBOLSUFFIX=_64` here, but I don't think we can do things differently if we want to be robust to name mangling differences between compilers.

**Comment by tkelman** [comment]
If you've tested it, I'll take your word for it. I'd rather spend effort on replacing arpack than patching it, but that's just me.

**Comment by stevengj** [comment]
@nalimilan, that sounds right.

**Comment by nalimilan** [comment]
@stevengj Any idea why the tests for bug 1315 are failing with ILP64? I saw you wrote the patch to use `BLASINT`, but that doesn't sound enough to make them work. IIUC, the tests are supposed to return 1000, 999, 998..., but they return 733.66, 0, 0... I don't see what could be wrong, except a wrong integer size somewhere (but where?).

**Comment by nalimilan** [comment]
@sylvestre Do you have any ideas about how to fix this? Other than that, the PR should be ready.

**Comment by sylvestre** [comment]
Sure, could you open a new bug about the CI integration? So that we don't forget when Debian/Ubuntu proposes this.

**Comment by nalimilan** [comment]
@sylvestre Thanks, but the tests are still failing with ILP64 enabled. Could you give me any pointers?

I've filed an issues about TravisCI at https://github.com/opencollab/arpack-ng/issues/33, but there's no guaranty that Ubuntu will include an ILP64 OpenBLAS.

BTW, any idea when you'll publish a new release?

**Comment by ViralBShah** [comment]
Apologies for chiming into such an old PR. 

I notice that `znaupd`, `zneupd`, `cnaupd`, and `cneupd` are included for name mangling with SYMBOLSUFFIX in the CMakeLists.txt only for Fortran and not for C. That means that the complex valued functions do not end up with the suffixed versions in the generated library.

Example build script for Julia's bundling of ARPACK: https://github.com/JuliaPackaging/Yggdrasil/blob/4a60c14c81f8f5752b19b23cb6b4e040a1b6ecc2/A/Arpack/build_tarballs.jl
```
➜  arpack-ng git:(master) nm /Users/viral/.julia/artifacts/87b6fe9f756585c40567136a5149f17b72856942/lib/libarpack.2.1.0.dylib| grep -i cnaupd
0000000000019570 T _cnaupd_
➜  arpack-ng git:(master) nm /Users/viral/.julia/artifacts/87b6fe9f756585c40567136a5149f17b72856942/lib/libarpack.2.1.0.dylib| grep -i dnaupd
000000000001ffc0 T _dnaupd_64_
```

**Comment by nalimilan** [comment]
At this point I have no idea whether this was just an oversight. Maybe make a PR to add them to the list?

**Comment by ViralBShah** [comment]
The `SCALARFUNS` and `COMPLEXFUNS` have the mangling defs added to `CMAKE_Fortran_FLAGS` whereas `CFUNS` are added to `CMAKE_C_FLAGS`.

**Comment by fghoussen** [comment]
> The SCALARFUNS and COMPLEXFUNS have the mangling defs

Use ICB: you won't need that anymore. Before ICB, symbols where defined "by hand" which is not portable.
https://github.com/opencollab/arpack-ng/tree/master#iso_c_binding-support

**Comment by ViralBShah** [comment]
We basically need BLAS and LAPACK calls with `_64` suffixes. I don't think ICB will help with that, IIUC.

**Comment by fghoussen** [comment]
> I notice that znaupd, zneupd, cnaupd, and cneupd ...

Only arpack `*n[ae]upd` symbols are concerned by the arpack-ng ICB option.

> We basically need BLAS and LAPACK calls with `_64` suffixes. I don't think ICB will help with that, IIUC.

BLAS, LAPACK can provide, or not, portable (ICB) or non-portable symbols (ideally each library should. For BLAS, LAPACK this is a huge and error-prone work with high impact: not sure if they provide ICB symbols, but, considering the involved work/impact, I'd understand they don't).

**Comment by fghoussen** [comment]
> The SCALARFUNS and COMPLEXFUNS have the mangling defs added

Ideally the "old way" of exporting (non-portable/exhaustive) symbols (using `SCALAR/COMPLEXFUNS) should be suppressed. ICB is the "new" portable (according to latest fortran standard) way to export symbols.

**Comment by fghoussen** [comment]
> I notice that znaupd, zneupd, cnaupd, and cneupd are included for name mangling with SYMBOLSUFFIX

Likely because all these symbols have not been "added by hand" here:

```
>> git grep COMPLEXFUNS
CMakeLists.txt:        set(COMPLEXFUNS, naitr napps naup2 naupd neigh neupd ngets statn getv0 sortc)
configure.ac:    COMPLEXFUNS="naitr napps naup2 naupd neigh neupd ngets statn getv0 sortc"

```

Try to add them here. If this creates expected symbols, you may even PR this here.

**Pull request merged**
